FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /App

COPY GoLondonAPI/*.csproj ./
RUN dotnet restore


COPY . ./
RUN dotnet publish GoLondon-Dotnet.sln -c Debug -o out
COPY appsettings.Development.json out/appsettings.Development.json

FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /App
COPY --from=build-env /App/out .
EXPOSE 6002
ENV ASPNETCORE_ENVIRONMENT=Development
ENV ASPNETCORE_URLS=http://*:6002
ENTRYPOINT ["dotnet", "GoLondonAPI.dll"]