name: Go-London-Builder

on:
  push:
    branches:
      - 'develop'
      - 'master'

jobs:
  docker-dev:
    name: Publish - Docker Dev
    runs-on: devapi
    if: github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v2
      - run: |
            docker stop GPAPIDev 2>/dev/null || true
            docker rm GPAPIDev 2>/dev/null || true
            cp /home/GaryPortal/API/DEV/appsettings.Development.json appsettings.Development.json
            docker build -t garyportalapi-dev -f Dockerfile.dev .
            docker create -p 0.0.0.0:5000:5000 --name "GPAPIDev" --restart unless-stopped --network="host" garyportalapi-dev
            docker start GPAPIDev
      - uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
  docker-prod:
    name: Publish - Docker Prod
    runs-on: prodapi
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - run: |
            docker stop GPAPIProd 2>/dev/null || true
            docker rm GPAPIProd 2>/dev/null || true
            cp /home/GaryPortal/API/PROD/appsettings.json appsettings.json
            docker build -t garyportalapi-prod -f Dockerfile.prod .
            docker create -p 0.0.0.0:6001:6001 --name "GPAPIProd" --restart unless-stopped --network="host" garyportalapi-prod
            docker start GPAPIProd
      - uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
  docker-v5:
    name: Publish - Docker v5 beta
    runs-on: v5api
    if: github.ref == 'refs/heads/feature/v5features'
    steps:
      - uses: actions/checkout@v2
      - run: |
            cp /home/GaryPortal/API/DEV/appsettings.Development.json appsettings.Development.json
            docker build -t garyportalapi-devv5 -f Dockerfile.devv5 .
            docker stop GPAPIDevV5 2>/dev/null || true
            docker rm GPAPIDevV5 2>/dev/null || true
            docker create -p 0.0.0.0:5101:5101 --name "GPAPIDevV5" --restart unless-stopped --network="host" garyportalapi-devv5
            docker start GPAPIDevV5
      - uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
